#ifndef PING_PONG_BUTTONS_H
#define PING_PONG_BUTTONS_H

#define BUTTON_DOWN_PLAYER_1_PIN   (0)  // D12 ACE-UNO
#define BUTTON_UP_PLAYER_1_PIN     (1)  // D11 ACE-UNO
#define BUTTON_DOWN_PLAYER_2_PIN   (2)  // D13 ACE-UNO
#define BUTTON_UP_PLAYER_2_PIN     (12) // D18 ACE-UNO

#define BUTTON_DOWN_PLAYER_1_PORT  GPIO_1
#define BUTTON_UP_PLAYER_1_PORT    GPIO_1
#define BUTTON_DOWN_PLAYER_2_PORT  GPIO_1
#define BUTTON_UP_PLAYER_2_PORT    GPIO_1

#endif
